run:
  timeout: 5m
  tests: true
  go: "1.25"

linters:
  enable:
    - govet
    - staticcheck
    - typecheck
    - errcheck
    - ineffassign
    - gofmt
    - unuse.github/d

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
